modLoader="javafml"
loaderVersion="[4,)"
license="Creative Commons Attribution-NonCommercial 3.0"

[[mods]]
modId="mintyirlplanets"
version="0.3.6"
displayName="\u00A7bMintyIRL Planets"
displayURL="https://mintychaos.com"
logoFile="logo.png"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="MintyIRL, MCreator"
description="This is a mod which adds dimensions inspired by planets. these dimensions are not remotely realistic"

# Start of user code block mod configuration
# End of user code block mod configuration


# Start of user code block custom mixins
# End of user code block custom mixins

[[dependencies.mintyirlplanets]]
    modId="neoforge"
    type="required"
    versionRange="[26.1.2.95,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.mintyirlplanets]]
    modId="minecraft"
    type="required"
    versionRange="[26.1.2]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration