/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.mintyirlplanets.init;

import net.neoforged.neoforge.registries.DeferredRegister;
import net.neoforged.neoforge.registries.DeferredBlock;
import net.neoforged.neoforge.event.BlockEntityTypeAddBlocksEvent;
import net.neoforged.fml.event.lifecycle.FMLClientSetupEvent;
import net.neoforged.fml.common.EventBusSubscriber;
import net.neoforged.bus.api.SubscribeEvent;
import net.neoforged.api.distmarker.Dist;

import net.minecraft.world.level.block.state.BlockBehaviour;
import net.minecraft.world.level.block.entity.BlockEntityType;
import net.minecraft.world.level.block.Block;
import net.minecraft.client.renderer.Sheets;

import net.mcreator.mintyirlplanets.block.*;
import net.mcreator.mintyirlplanets.MintyirlplanetsMod;

import java.util.function.Function;

@EventBusSubscriber
public class MintyirlplanetsModBlocks {
	public static final DeferredRegister.Blocks REGISTRY = DeferredRegister.createBlocks(MintyirlplanetsMod.MODID);
	public static final DeferredBlock<Block> MOON_ROCK;
	public static final DeferredBlock<Block> DARK_MOON_ROCK;
	public static final DeferredBlock<Block> MOONSHROOM_MOSS;
	public static final DeferredBlock<Block> TERRACELIUM_MOSS;
	public static final DeferredBlock<Block> THE_MOON_PORTAL;
	public static final DeferredBlock<Block> DREAMDROP_ORE;
	public static final DeferredBlock<Block> DREAMDROP_BLOCK;
	public static final DeferredBlock<Block> DAMNED_WOOD;
	public static final DeferredBlock<Block> DAMNED_LOG;
	public static final DeferredBlock<Block> DAMNED_PLANKS;
	public static final DeferredBlock<Block> DAMNED_LEAVES;
	public static final DeferredBlock<Block> DAMNED_STAIRS;
	public static final DeferredBlock<Block> DAMNED_SLAB;
	public static final DeferredBlock<Block> DAMNED_FENCE;
	public static final DeferredBlock<Block> DAMNED_FENCE_GATE;
	public static final DeferredBlock<Block> DAMNED_PRESSURE_PLATE;
	public static final DeferredBlock<Block> DAMNED_BUTTON;
	public static final DeferredBlock<Block> SIVER_ORE;
	public static final DeferredBlock<Block> SIVER_BLOCK;
	public static final DeferredBlock<Block> ALUMINUM_ORE;
	public static final DeferredBlock<Block> ALUMINUM_BLOCK;
	public static final DeferredBlock<Block> ALUMINEUM_BLOCK;
	public static final DeferredBlock<Block> MOONSHROOM_2_WOOD;
	public static final DeferredBlock<Block> MOONSHROOM_2_LOG;
	public static final DeferredBlock<Block> MOONSHROOM_2_PLANKS;
	public static final DeferredBlock<Block> MOONSHROOM_2_LEAVES;
	public static final DeferredBlock<Block> MOONSHROOM_2_STAIRS;
	public static final DeferredBlock<Block> MOONSHROOM_2_SLAB;
	public static final DeferredBlock<Block> MOONSHROOM_2_FENCE;
	public static final DeferredBlock<Block> MOONSHROOM_2_FENCE_GATE;
	public static final DeferredBlock<Block> MOONSHROOM_2_PRESSURE_PLATE;
	public static final DeferredBlock<Block> MOONSHROOM_2_BUTTON;
	public static final DeferredBlock<Block> MOONSHROOM_SPORESCONNECTOR;
	public static final DeferredBlock<Block> MOONSHROOM_SPORES;
	public static final DeferredBlock<Block> MOONSHROOM_STEM;
	public static final DeferredBlock<Block> KRYPTONIUM_ORE;
	public static final DeferredBlock<Block> KRYPTONIUM_BLOCK;
	public static final DeferredBlock<Block> FERROUS_SAND;
	public static final DeferredBlock<Block> MARS_PORTAL;
	public static final DeferredBlock<Block> CORESTONE;
	public static final DeferredBlock<Block> CROATIAN_WOOD;
	public static final DeferredBlock<Block> CROATIAN_LOG;
	public static final DeferredBlock<Block> CROATIAN_PLANKS;
	public static final DeferredBlock<Block> CROATIAN_LEAVES;
	public static final DeferredBlock<Block> CROATIAN_STAIRS;
	public static final DeferredBlock<Block> CROATIAN_SLAB;
	public static final DeferredBlock<Block> CROATIAN_FENCE;
	public static final DeferredBlock<Block> CROATIAN_FENCE_GATE;
	public static final DeferredBlock<Block> CROATIAN_PRESSURE_PLATE;
	public static final DeferredBlock<Block> CROATIAN_BUTTON;
	public static final DeferredBlock<Block> ADAMANTIUMM_ORE;
	public static final DeferredBlock<Block> ADAMANTIUMM_BLOCK;
	public static final DeferredBlock<Block> DEMONIC_ORE;
	public static final DeferredBlock<Block> DEMONIC_BLOCK;
	public static final DeferredBlock<Block> STRANGE_STONE;
	public static final DeferredBlock<Block> STRANGE_ROCK;
	public static final DeferredBlock<Block> MOSSY_STRANGE_STONE;
	public static final DeferredBlock<Block> AQUAPHER_FLOWER;
	public static final DeferredBlock<Block> SATURN_PORTAL;
	public static final DeferredBlock<Block> STAR_FLOWER;
	public static final DeferredBlock<Block> SMOTHE_BONE;
	public static final DeferredBlock<Block> BONE_BRICKS;
	public static final DeferredBlock<Block> CHIZZELED_BONE;
	public static final DeferredBlock<Block> CRACKED_BONE_BRICK;
	public static final DeferredBlock<Block> SMOTH_BONE_SLAB;
	public static final DeferredBlock<Block> BONE_BRICK_SLAB;
	public static final DeferredBlock<Block> CHIZZELED_BONE_SLAB;
	public static final DeferredBlock<Block> CRACKED_BONE_BRICK_SLAB;
	public static final DeferredBlock<Block> BONE_SLAB;
	public static final DeferredBlock<Block> GUSTAVIUM;
	public static final DeferredBlock<Block> TOXIC_WASTE;
	public static final DeferredBlock<Block> FIBERGLASS;
	public static final DeferredBlock<Block> CLEAR_PLASTC;
	public static final DeferredBlock<Block> GLOWING;
	public static final DeferredBlock<Block> BRIMSTONE_ORE;
	public static final DeferredBlock<Block> BRIMSTONE_BLOCK;
	public static final DeferredBlock<Block> SOULSTONE_ORE;
	public static final DeferredBlock<Block> SOULSTONE_BLOCK;
	public static final DeferredBlock<Block> FRAGRENT_WOOD;
	public static final DeferredBlock<Block> FRAGRENT_LOG;
	public static final DeferredBlock<Block> FRAGRENT_PLANKS;
	public static final DeferredBlock<Block> FRAGRENT_LEAVES;
	public static final DeferredBlock<Block> FRAGRENT_STAIRS;
	public static final DeferredBlock<Block> FRAGRENT_SLAB;
	public static final DeferredBlock<Block> FRAGRENT_FENCE;
	public static final DeferredBlock<Block> FRAGRENT_FENCE_GATE;
	public static final DeferredBlock<Block> FRAGRENT_PRESSURE_PLATE;
	public static final DeferredBlock<Block> FRAGRENT_BUTTON;
	public static final DeferredBlock<Block> REINFORCED_GLASS;
	public static final DeferredBlock<Block> TOSSER_BUSH;
	public static final DeferredBlock<Block> CROK_VINE;
	public static final DeferredBlock<Block> CROK_BULB;
	public static final DeferredBlock<Block> FOSSIL;
	public static final DeferredBlock<Block> FANCY_CANDLE;
	public static final DeferredBlock<Block> UNLIT_FANCY_CANDLE;
	public static final DeferredBlock<Block> STRIPPED_FRAGRENT_WOOD;
	public static final DeferredBlock<Block> STRIPPED_FRAGRENT_LOG;
	public static final DeferredBlock<Block> H_CRYSTAL;
	public static final DeferredBlock<Block> METEORITE;
	public static final DeferredBlock<Block> CHLORITE;
	public static final DeferredBlock<Block> LIGHT_MOON_STONE;
	public static final DeferredBlock<Block> DARK_MOON_STONE;
	public static final DeferredBlock<Block> RAW_SILVER_BLOCK;
	public static final DeferredBlock<Block> SNAP_TRAP;
	public static final DeferredBlock<Block> POISON_SNAP_TRAP;
	public static final DeferredBlock<Block> MOON_MUSHROOM;
	public static final DeferredBlock<Block> HORRID_FUNGUS;
	public static final DeferredBlock<Block> HORRID_MERCURY;
	public static final DeferredBlock<Block> HORRID_FUNGUS_DEACTIVATED;
	public static final DeferredBlock<Block> DORMANT_HORRID_MERCURY;
	public static final DeferredBlock<Block> BLOOD_CACTUS;
	public static final DeferredBlock<Block> THORN_BERRY_BUSH;
	public static final DeferredBlock<Block> EMERALD_BRICKS;
	public static final DeferredBlock<Block> EMERALD_SLATES;
	public static final DeferredBlock<Block> EMERALD_SLATE_STAIRS;
	public static final DeferredBlock<Block> EMERALD_TRAPDOOR;
	public static final DeferredBlock<Block> EMERALD_BRICK_STAIRS;
	public static final DeferredBlock<Block> EMERALD_BRICK_SLAB;
	public static final DeferredBlock<Block> EMERALD_SLATE_SLAB;
	public static final DeferredBlock<Block> CHIZZLED_EMERALD;
	public static final DeferredBlock<Block> NETTLE_VINES;
	public static final DeferredBlock<Block> CAVE_MOSS;
	public static final DeferredBlock<Block> SUBCONSIUS_LOG;
	public static final DeferredBlock<Block> SUBCONSIUS_WOOD;
	public static final DeferredBlock<Block> STRIPPED_SUBCONSIUS_LOG;
	public static final DeferredBlock<Block> STRIPPED_SUBCONSIUS_WOOD;
	public static final DeferredBlock<Block> SUBCONSIUS_PLANKS;
	public static final DeferredBlock<Block> SUBCONSIUS_LEAVES;
	public static final DeferredBlock<Block> SUBCONSIUS_STAIRS;
	public static final DeferredBlock<Block> SUBCONSIUS_SLAB;
	public static final DeferredBlock<Block> SUBCONSIUS_FENCE;
	public static final DeferredBlock<Block> SUBCONSIUS_FENCE_GATE;
	public static final DeferredBlock<Block> SUBCONSIUS_DOOR;
	public static final DeferredBlock<Block> SUBCONSIUS_TRAPDOOR;
	public static final DeferredBlock<Block> SUBCONSIUS_PRESSURE_PLATE;
	public static final DeferredBlock<Block> SUBCONSIUS_BUTTON;
	public static final DeferredBlock<Block> SUBCONSIUS_SIGN;
	public static final DeferredBlock<Block> SUBCONSIUS_WALL_SIGN;
	public static final DeferredBlock<Block> SUBCONSIUS_HANGING_SIGN;
	public static final DeferredBlock<Block> SUBCONSIUS_WALL_HANGING_SIGN;
	public static final DeferredBlock<Block> UNCONSIUM_SAPLING;
	public static final DeferredBlock<Block> CHEESE;
	static {
		MOON_ROCK = register("moon_rock", MoonRockBlock::new);
		DARK_MOON_ROCK = register("dark_moon_rock", DarkMoonRockBlock::new);
		MOONSHROOM_MOSS = register("moonshroom_moss", MoonshroomMossBlock::new);
		TERRACELIUM_MOSS = register("terracelium_moss", TerraceliumMossBlock::new);
		THE_MOON_PORTAL = register("the_moon_portal", TheMoonPortalBlock::new);
		DREAMDROP_ORE = register("dreamdrop_ore", DreamdropOreBlock::new);
		DREAMDROP_BLOCK = register("dreamdrop_block", DreamdropBlockBlock::new);
		DAMNED_WOOD = register("damned_wood", DamnedWoodBlock::new);
		DAMNED_LOG = register("damned_log", DamnedLogBlock::new);
		DAMNED_PLANKS = register("damned_planks", DamnedPlanksBlock::new);
		DAMNED_LEAVES = register("damned_leaves", DamnedLeavesBlock::new);
		DAMNED_STAIRS = register("damned_stairs", DamnedStairsBlock::new);
		DAMNED_SLAB = register("damned_slab", DamnedSlabBlock::new);
		DAMNED_FENCE = register("damned_fence", DamnedFenceBlock::new);
		DAMNED_FENCE_GATE = register("damned_fence_gate", DamnedFenceGateBlock::new);
		DAMNED_PRESSURE_PLATE = register("damned_pressure_plate", DamnedPressurePlateBlock::new);
		DAMNED_BUTTON = register("damned_button", DamnedButtonBlock::new);
		SIVER_ORE = register("siver_ore", SiverOreBlock::new);
		SIVER_BLOCK = register("siver_block", SiverBlockBlock::new);
		ALUMINUM_ORE = register("aluminum_ore", AluminumOreBlock::new);
		ALUMINUM_BLOCK = register("aluminum_block", AluminumBlockBlock::new);
		ALUMINEUM_BLOCK = register("alumineum_block", AlumineumBlockBlock::new);
		MOONSHROOM_2_WOOD = register("moonshroom_2_wood", Moonshroom2WoodBlock::new);
		MOONSHROOM_2_LOG = register("moonshroom_2_log", Moonshroom2LogBlock::new);
		MOONSHROOM_2_PLANKS = register("moonshroom_2_planks", Moonshroom2PlanksBlock::new);
		MOONSHROOM_2_LEAVES = register("moonshroom_2_leaves", Moonshroom2LeavesBlock::new);
		MOONSHROOM_2_STAIRS = register("moonshroom_2_stairs", Moonshroom2StairsBlock::new);
		MOONSHROOM_2_SLAB = register("moonshroom_2_slab", Moonshroom2SlabBlock::new);
		MOONSHROOM_2_FENCE = register("moonshroom_2_fence", Moonshroom2FenceBlock::new);
		MOONSHROOM_2_FENCE_GATE = register("moonshroom_2_fence_gate", Moonshroom2FenceGateBlock::new);
		MOONSHROOM_2_PRESSURE_PLATE = register("moonshroom_2_pressure_plate", Moonshroom2PressurePlateBlock::new);
		MOONSHROOM_2_BUTTON = register("moonshroom_2_button", Moonshroom2ButtonBlock::new);
		MOONSHROOM_SPORESCONNECTOR = register("moonshroom_sporesconnector", MoonshroomSporesconnectorBlock::new);
		MOONSHROOM_SPORES = register("moonshroom_spores", MoonshroomSporesBlock::new);
		MOONSHROOM_STEM = register("moonshroom_stem", MoonshroomStemBlock::new);
		KRYPTONIUM_ORE = register("kryptonium_ore", KryptoniumOreBlock::new);
		KRYPTONIUM_BLOCK = register("kryptonium_block", KryptoniumBlockBlock::new);
		FERROUS_SAND = register("ferrous_sand", FerrousSandBlock::new);
		MARS_PORTAL = register("mars_portal", MarsPortalBlock::new);
		CORESTONE = register("corestone", CorestoneBlock::new);
		CROATIAN_WOOD = register("croatian_wood", CroatianWoodBlock::new);
		CROATIAN_LOG = register("croatian_log", CroatianLogBlock::new);
		CROATIAN_PLANKS = register("croatian_planks", CroatianPlanksBlock::new);
		CROATIAN_LEAVES = register("croatian_leaves", CroatianLeavesBlock::new);
		CROATIAN_STAIRS = register("croatian_stairs", CroatianStairsBlock::new);
		CROATIAN_SLAB = register("croatian_slab", CroatianSlabBlock::new);
		CROATIAN_FENCE = register("croatian_fence", CroatianFenceBlock::new);
		CROATIAN_FENCE_GATE = register("croatian_fence_gate", CroatianFenceGateBlock::new);
		CROATIAN_PRESSURE_PLATE = register("croatian_pressure_plate", CroatianPressurePlateBlock::new);
		CROATIAN_BUTTON = register("croatian_button", CroatianButtonBlock::new);
		ADAMANTIUMM_ORE = register("adamantiumm_ore", AdamantiummOreBlock::new);
		ADAMANTIUMM_BLOCK = register("adamantiumm_block", AdamantiummBlockBlock::new);
		DEMONIC_ORE = register("demonic_ore", DemonicOreBlock::new);
		DEMONIC_BLOCK = register("demonic_block", DemonicBlockBlock::new);
		STRANGE_STONE = register("strange_stone", StrangeStoneBlock::new);
		STRANGE_ROCK = register("strange_rock", StrangeRockBlock::new);
		MOSSY_STRANGE_STONE = register("mossy_strange_stone", MossyStrangeStoneBlock::new);
		AQUAPHER_FLOWER = register("aquapher_flower", AquapherFlowerBlock::new);
		SATURN_PORTAL = register("saturn_portal", SaturnPortalBlock::new);
		STAR_FLOWER = register("star_flower", StarFlowerBlock::new);
		SMOTHE_BONE = register("smothe_bone", SmotheBoneBlock::new);
		BONE_BRICKS = register("bone_bricks", BoneBricksBlock::new);
		CHIZZELED_BONE = register("chizzeled_bone", ChizzeledBoneBlock::new);
		CRACKED_BONE_BRICK = register("cracked_bone_brick", CrackedBoneBrickBlock::new);
		SMOTH_BONE_SLAB = register("smoth_bone_slab", SmothBoneSlabBlock::new);
		BONE_BRICK_SLAB = register("bone_brick_slab", BoneBrickSlabBlock::new);
		CHIZZELED_BONE_SLAB = register("chizzeled_bone_slab", ChizzeledBoneSlabBlock::new);
		CRACKED_BONE_BRICK_SLAB = register("cracked_bone_brick_slab", CrackedBoneBrickSlabBlock::new);
		BONE_SLAB = register("bone_slab", BoneSlabBlock::new);
		GUSTAVIUM = register("gustavium", GustaviumBlock::new);
		TOXIC_WASTE = register("toxic_waste", ToxicWasteBlock::new);
		FIBERGLASS = register("fiberglass", FiberglassBlock::new);
		CLEAR_PLASTC = register("clear_plastc", ClearPlastcBlock::new);
		GLOWING = register("glowing", GlowingBlock::new);
		BRIMSTONE_ORE = register("brimstone_ore", BrimstoneOreBlock::new);
		BRIMSTONE_BLOCK = register("brimstone_block", BrimstoneBlockBlock::new);
		SOULSTONE_ORE = register("soulstone_ore", SoulstoneOreBlock::new);
		SOULSTONE_BLOCK = register("soulstone_block", SoulstoneBlockBlock::new);
		FRAGRENT_WOOD = register("fragrent_wood", FragrentWoodBlock::new);
		FRAGRENT_LOG = register("fragrent_log", FragrentLogBlock::new);
		FRAGRENT_PLANKS = register("fragrent_planks", FragrentPlanksBlock::new);
		FRAGRENT_LEAVES = register("fragrent_leaves", FragrentLeavesBlock::new);
		FRAGRENT_STAIRS = register("fragrent_stairs", FragrentStairsBlock::new);
		FRAGRENT_SLAB = register("fragrent_slab", FragrentSlabBlock::new);
		FRAGRENT_FENCE = register("fragrent_fence", FragrentFenceBlock::new);
		FRAGRENT_FENCE_GATE = register("fragrent_fence_gate", FragrentFenceGateBlock::new);
		FRAGRENT_PRESSURE_PLATE = register("fragrent_pressure_plate", FragrentPressurePlateBlock::new);
		FRAGRENT_BUTTON = register("fragrent_button", FragrentButtonBlock::new);
		REINFORCED_GLASS = register("reinforced_glass", ReinforcedGlassBlock::new);
		TOSSER_BUSH = register("tosser_bush", TosserBushBlock::new);
		CROK_VINE = register("crok_vine", CrokVineBlock::new);
		CROK_BULB = register("crok_bulb", CrokBulbBlock::new);
		FOSSIL = register("fossil", FossilBlock::new);
		FANCY_CANDLE = register("fancy_candle", FancyCandleBlock::new);
		UNLIT_FANCY_CANDLE = register("unlit_fancy_candle", UnlitFancyCandleBlock::new);
		STRIPPED_FRAGRENT_WOOD = register("stripped_fragrent_wood", StrippedFragrentWoodBlock::new);
		STRIPPED_FRAGRENT_LOG = register("stripped_fragrent_log", StrippedFragrentLogBlock::new);
		H_CRYSTAL = register("h_crystal", HCrystalBlock::new);
		METEORITE = register("meteorite", MeteoriteBlock::new);
		CHLORITE = register("chlorite", ChlorineBlock::new);
		LIGHT_MOON_STONE = register("light_moon_stone", LightMoonStoneBlock::new);
		DARK_MOON_STONE = register("dark_moon_stone", DarkMoonStoneBlock::new);
		RAW_SILVER_BLOCK = register("raw_silver_block", RawSilverBlockBlock::new);
		SNAP_TRAP = register("snap_trap", SnapTrapBlock::new);
		POISON_SNAP_TRAP = register("poison_snap_trap", PoisonSnapTrapBlock::new);
		MOON_MUSHROOM = register("moon_mushroom", MoonMushroomBlock::new);
		HORRID_FUNGUS = register("horrid_fungus", HorridFungusBlock::new);
		HORRID_MERCURY = register("horrid_mercury", HorridMercuryBlock::new);
		HORRID_FUNGUS_DEACTIVATED = register("horrid_fungus_deactivated", HorridFungusDeactivatedBlock::new);
		DORMANT_HORRID_MERCURY = register("dormant_horrid_mercury", DormantHorridMercuryBlock::new);
		BLOOD_CACTUS = register("blood_cactus", BloodCactusBlock::new);
		THORN_BERRY_BUSH = register("thorn_berry_bush", ThornBerryBushBlock::new);
		EMERALD_BRICKS = register("emerald_bricks", EmeraldBricksBlock::new);
		EMERALD_SLATES = register("emerald_slates", EmeraldSlatesBlock::new);
		EMERALD_SLATE_STAIRS = register("emerald_slate_stairs", EmeraldSlateStairsBlock::new);
		EMERALD_TRAPDOOR = register("emerald_trapdoor", EmeraldTrapdoorBlock::new);
		EMERALD_BRICK_STAIRS = register("emerald_brick_stairs", EmeraldBrickStairsBlock::new);
		EMERALD_BRICK_SLAB = register("emerald_brick_slab", EmeraldBrickSlabBlock::new);
		EMERALD_SLATE_SLAB = register("emerald_slate_slab", EmeraldSlateSlabBlock::new);
		CHIZZLED_EMERALD = register("chizzled_emerald", ChizzledEmeraldBlock::new);
		NETTLE_VINES = register("nettle_vines", NettleVinesBlock::new);
		CAVE_MOSS = register("cave_moss", CaveMossBlock::new);
		SUBCONSIUS_LOG = register("subconsius_log", SubconsiusLogBlock::new);
		SUBCONSIUS_WOOD = register("subconsius_wood", SubconsiusWoodBlock::new);
		STRIPPED_SUBCONSIUS_LOG = register("stripped_subconsius_log", StrippedSubconsiusLogBlock::new);
		STRIPPED_SUBCONSIUS_WOOD = register("stripped_subconsius_wood", StrippedSubconsiusWoodBlock::new);
		SUBCONSIUS_PLANKS = register("subconsius_planks", SubconsiusPlanksBlock::new);
		SUBCONSIUS_LEAVES = register("subconsius_leaves", SubconsiusLeavesBlock::new);
		SUBCONSIUS_STAIRS = register("subconsius_stairs", SubconsiusStairsBlock::new);
		SUBCONSIUS_SLAB = register("subconsius_slab", SubconsiusSlabBlock::new);
		SUBCONSIUS_FENCE = register("subconsius_fence", SubconsiusFenceBlock::new);
		SUBCONSIUS_FENCE_GATE = register("subconsius_fence_gate", SubconsiusFenceGateBlock::new);
		SUBCONSIUS_DOOR = register("subconsius_door", SubconsiusDoorBlock::new);
		SUBCONSIUS_TRAPDOOR = register("subconsius_trapdoor", SubconsiusTrapdoorBlock::new);
		SUBCONSIUS_PRESSURE_PLATE = register("subconsius_pressure_plate", SubconsiusPressurePlateBlock::new);
		SUBCONSIUS_BUTTON = register("subconsius_button", SubconsiusButtonBlock::new);
		SUBCONSIUS_SIGN = register("subconsius_sign", SubconsiusSignBlock::new);
		SUBCONSIUS_WALL_SIGN = register("subconsius_wall_sign", SubconsiusWallSignBlock::new);
		SUBCONSIUS_HANGING_SIGN = register("subconsius_hanging_sign", SubconsiusHangingSignBlock::new);
		SUBCONSIUS_WALL_HANGING_SIGN = register("subconsius_wall_hanging_sign", SubconsiusWallHangingSignBlock::new);
		UNCONSIUM_SAPLING = register("unconsium_sapling", UnconsiumSaplingBlock::new);
		CHEESE = register("cheese", CheeseBlock::new);
	}

	// Start of user code block custom blocks
	// End of user code block custom blocks
	private static <B extends Block> DeferredBlock<B> register(String name, Function<BlockBehaviour.Properties, ? extends B> supplier) {
		return REGISTRY.registerBlock(name, supplier);
	}

	@EventBusSubscriber(Dist.CLIENT)
	public static class BlocksClientSideHandler {
		@SubscribeEvent
		public static void clientSetup(FMLClientSetupEvent event) {
			Sheets.addWoodType(MintyirlplanetsModWoodTypes.SUBCONSIUS_SIGN_WOOD_TYPE);
			Sheets.addWoodType(MintyirlplanetsModWoodTypes.SUBCONSIUS_HANGING_SIGN_WOOD_TYPE);
		}
	}

	@SubscribeEvent
	public static void registerSigns(BlockEntityTypeAddBlocksEvent event) {
		event.modify(BlockEntityType.SIGN, SUBCONSIUS_SIGN.get(), SUBCONSIUS_WALL_SIGN.get());
		event.modify(BlockEntityType.HANGING_SIGN, SUBCONSIUS_HANGING_SIGN.get(), SUBCONSIUS_WALL_HANGING_SIGN.get());
	}
}