/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.mintyirlplanets.init;

import net.neoforged.neoforge.registries.DeferredRegister;
import net.neoforged.neoforge.registries.DeferredItem;
import net.neoforged.neoforge.registries.DeferredHolder;
import net.neoforged.neoforge.fluids.capability.wrappers.FluidBucketWrapper;
import net.neoforged.neoforge.capabilities.RegisterCapabilitiesEvent;
import net.neoforged.neoforge.capabilities.Capabilities;
import net.neoforged.fml.common.EventBusSubscriber;
import net.neoforged.bus.api.SubscribeEvent;

import net.minecraft.world.level.block.Block;
import net.minecraft.world.item.SpawnEggItem;
import net.minecraft.world.item.Rarity;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.BlockItem;

import net.mcreator.mintyirlplanets.item.*;
import net.mcreator.mintyirlplanets.block.FragrentLogBlock;
import net.mcreator.mintyirlplanets.block.DarkMoonRockBlock;
import net.mcreator.mintyirlplanets.block.DamnedLogBlock;
import net.mcreator.mintyirlplanets.block.BrimstoneOreBlock;
import net.mcreator.mintyirlplanets.MintyirlplanetsMod;

import java.util.function.Function;

@EventBusSubscriber
public class MintyirlplanetsModItems {
	public static final DeferredRegister.Items REGISTRY = DeferredRegister.createItems(MintyirlplanetsMod.MODID);
	public static final DeferredItem<Item> DEBUG_PICK;
	public static final DeferredItem<Item> DEBUGGER_SPAWN_EGG;
	public static final DeferredItem<Item> DEBUGGER_ARMOUR_HELMET;
	public static final DeferredItem<Item> DEBUGGER_ARMOUR_CHESTPLATE;
	public static final DeferredItem<Item> DEBUGGER_ARMOUR_LEGGINGS;
	public static final DeferredItem<Item> DEBUGGER_ARMOUR_BOOTS;
	public static final DeferredItem<Item> DISC_1;
	public static final DeferredItem<Item> DISC_2;
	public static final DeferredItem<Item> DUMMY_1_HELMET;
	public static final DeferredItem<Item> DUMMY_1_CHESTPLATE;
	public static final DeferredItem<Item> DUMMY_1_LEGGINGS;
	public static final DeferredItem<Item> DUMMY_1_BOOTS;
	public static final DeferredItem<Item> DUMMY_2_HELMET;
	public static final DeferredItem<Item> DUMMY_2_CHESTPLATE;
	public static final DeferredItem<Item> DUMMY_2_LEGGINGS;
	public static final DeferredItem<Item> DUMMY_2_BOOTS;
	public static final DeferredItem<Item> MOON_ROCK;
	public static final DeferredItem<Item> DARK_MOON_ROCK;
	public static final DeferredItem<Item> MOONSHROOM_MOSS;
	public static final DeferredItem<Item> TERRACELIUM_MOSS;
	public static final DeferredItem<Item> THE_MOON;
	public static final DeferredItem<Item> DREAMDROP;
	public static final DeferredItem<Item> DREAMDROP_ORE;
	public static final DeferredItem<Item> DREAMDROP_BLOCK;
	public static final DeferredItem<Item> DREAMDROP_PICKAXE;
	public static final DeferredItem<Item> DREAMDROP_AXE;
	public static final DeferredItem<Item> DREAMDROP_SWORD;
	public static final DeferredItem<Item> DREAMDROP_SHOVEL;
	public static final DeferredItem<Item> DREAMDROP_HOE;
	public static final DeferredItem<Item> DREAMDROP_ARMOR_HELMET;
	public static final DeferredItem<Item> DREAMDROP_ARMOR_CHESTPLATE;
	public static final DeferredItem<Item> DREAMDROP_ARMOR_LEGGINGS;
	public static final DeferredItem<Item> DREAMDROP_ARMOR_BOOTS;
	public static final DeferredItem<Item> DAMNED_WOOD;
	public static final DeferredItem<Item> DAMNED_LOG;
	public static final DeferredItem<Item> DAMNED_PLANKS;
	public static final DeferredItem<Item> DAMNED_LEAVES;
	public static final DeferredItem<Item> DAMNED_STAIRS;
	public static final DeferredItem<Item> DAMNED_SLAB;
	public static final DeferredItem<Item> DAMNED_FENCE;
	public static final DeferredItem<Item> DAMNED_FENCE_GATE;
	public static final DeferredItem<Item> DAMNED_PRESSURE_PLATE;
	public static final DeferredItem<Item> DAMNED_BUTTON;
	public static final DeferredItem<Item> GLUCOSIDE_EXTRACT;
	public static final DeferredItem<Item> HELL_FRUIT;
	public static final DeferredItem<Item> REAPER_SPAWN_EGG;
	public static final DeferredItem<Item> SIVER_INGOT;
	public static final DeferredItem<Item> SIVER_ORE;
	public static final DeferredItem<Item> SIVER_BLOCK;
	public static final DeferredItem<Item> SIVER_PICKAXE;
	public static final DeferredItem<Item> SIVER_AXE;
	public static final DeferredItem<Item> SIVER_SWORD;
	public static final DeferredItem<Item> SIVER_SHOVEL;
	public static final DeferredItem<Item> SIVER_HOE;
	public static final DeferredItem<Item> SIVER_ARMOR_HELMET;
	public static final DeferredItem<Item> SIVER_ARMOR_CHESTPLATE;
	public static final DeferredItem<Item> SIVER_ARMOR_LEGGINGS;
	public static final DeferredItem<Item> SIVER_ARMOR_BOOTS;
	public static final DeferredItem<Item> ALUMINUM_ORE;
	public static final DeferredItem<Item> ALUMINUM_BLOCK;
	public static final DeferredItem<Item> ALUMINEUM;
	public static final DeferredItem<Item> ALUMINEUM_BLOCK;
	public static final DeferredItem<Item> ALUMINEUM_PICKAXE;
	public static final DeferredItem<Item> ALUMINEUM_AXE;
	public static final DeferredItem<Item> ALUMINEUM_SWORD;
	public static final DeferredItem<Item> ALUMINEUM_SHOVEL;
	public static final DeferredItem<Item> ALUMINEUM_HOE;
	public static final DeferredItem<Item> ALUMINEUM_ARMOR_HELMET;
	public static final DeferredItem<Item> ALUMINEUM_ARMOR_CHESTPLATE;
	public static final DeferredItem<Item> ALUMINEUM_ARMOR_LEGGINGS;
	public static final DeferredItem<Item> ALUMINEUM_ARMOR_BOOTS;
	public static final DeferredItem<Item> BAUXITE;
	public static final DeferredItem<Item> MOONSHROOM_2_WOOD;
	public static final DeferredItem<Item> MOONSHROOM_2_LOG;
	public static final DeferredItem<Item> MOONSHROOM_2_PLANKS;
	public static final DeferredItem<Item> MOONSHROOM_2_LEAVES;
	public static final DeferredItem<Item> MOONSHROOM_2_STAIRS;
	public static final DeferredItem<Item> MOONSHROOM_2_SLAB;
	public static final DeferredItem<Item> MOONSHROOM_2_FENCE;
	public static final DeferredItem<Item> MOONSHROOM_2_FENCE_GATE;
	public static final DeferredItem<Item> MOONSHROOM_2_PRESSURE_PLATE;
	public static final DeferredItem<Item> MOONSHROOM_2_BUTTON;
	public static final DeferredItem<Item> MOONSHROOM_SPORESCONNECTOR;
	public static final DeferredItem<Item> MOONSHROOM_SPORES;
	public static final DeferredItem<Item> MOONSHROOM_STEM;
	public static final DeferredItem<Item> COLD_DUST;
	public static final DeferredItem<Item> LAZER_SHOOTER;
	public static final DeferredItem<Item> EYEZOR_SPAWN_EGG;
	public static final DeferredItem<Item> DARK_MOONDISC;
	public static final DeferredItem<Item> STRANGE_ENERGY;
	public static final DeferredItem<Item> ANTIMATTER;
	public static final DeferredItem<Item> KRYPTONIUM;
	public static final DeferredItem<Item> KRYPTONIUM_ORE;
	public static final DeferredItem<Item> KRYPTONIUM_BLOCK;
	public static final DeferredItem<Item> KRYPTONIUM_PICKAXE;
	public static final DeferredItem<Item> KRYPTONIUM_AXE;
	public static final DeferredItem<Item> KRYPTONIUM_SWORD;
	public static final DeferredItem<Item> KRYPTONIUM_SHOVEL;
	public static final DeferredItem<Item> KRYPTONIUM_HOE;
	public static final DeferredItem<Item> KRYPTONIUM_ARMOR_HELMET;
	public static final DeferredItem<Item> KRYPTONIUM_ARMOR_CHESTPLATE;
	public static final DeferredItem<Item> KRYPTONIUM_ARMOR_LEGGINGS;
	public static final DeferredItem<Item> KRYPTONIUM_ARMOR_BOOTS;
	public static final DeferredItem<Item> THE_CRUSHER_SPAWN_EGG;
	public static final DeferredItem<Item> FERROUS_SAND;
	public static final DeferredItem<Item> SPACE_HELMET;
	public static final DeferredItem<Item> SPACE_CHESTPLATE;
	public static final DeferredItem<Item> SPACE_LEGGINGS;
	public static final DeferredItem<Item> SPACE_BOOTS;
	public static final DeferredItem<Item> MARS;
	public static final DeferredItem<Item> MARTIAN_SPAWN_EGG;
	public static final DeferredItem<Item> SHRUMPHER_SPAWN_EGG;
	public static final DeferredItem<Item> CORESTONE;
	public static final DeferredItem<Item> CROATIAN_WOOD;
	public static final DeferredItem<Item> CROATIAN_LOG;
	public static final DeferredItem<Item> CROATIAN_PLANKS;
	public static final DeferredItem<Item> CROATIAN_LEAVES;
	public static final DeferredItem<Item> CROATIAN_STAIRS;
	public static final DeferredItem<Item> CROATIAN_SLAB;
	public static final DeferredItem<Item> CROATIAN_FENCE;
	public static final DeferredItem<Item> CROATIAN_FENCE_GATE;
	public static final DeferredItem<Item> CROATIAN_PRESSURE_PLATE;
	public static final DeferredItem<Item> CROATIAN_BUTTON;
	public static final DeferredItem<Item> MUSIC_DISC_MARS;
	public static final DeferredItem<Item> ADAMANTIUMM;
	public static final DeferredItem<Item> ADAMANTIUMM_ORE;
	public static final DeferredItem<Item> ADAMANTIUMM_BLOCK;
	public static final DeferredItem<Item> ADAMANTIUMM_PICKAXE;
	public static final DeferredItem<Item> ADAMANTIUMM_AXE;
	public static final DeferredItem<Item> ADAMANTIUMM_SWORD;
	public static final DeferredItem<Item> ADAMANTIUMM_SHOVEL;
	public static final DeferredItem<Item> ADAMANTIUMM_HOE;
	public static final DeferredItem<Item> ADAMANTIUMM_ARMOR_HELMET;
	public static final DeferredItem<Item> ADAMANTIUMM_ARMOR_CHESTPLATE;
	public static final DeferredItem<Item> ADAMANTIUMM_ARMOR_LEGGINGS;
	public static final DeferredItem<Item> ADAMANTIUMM_ARMOR_BOOTS;
	public static final DeferredItem<Item> RAW_ADAMANTIUM;
	public static final DeferredItem<Item> DEMONIC_INGOT;
	public static final DeferredItem<Item> DEMONIC_ORE;
	public static final DeferredItem<Item> DEMONIC_BLOCK;
	public static final DeferredItem<Item> DEMONIC_PICKAXE;
	public static final DeferredItem<Item> DEMONIC_AXE;
	public static final DeferredItem<Item> DEMONIC_SWORD;
	public static final DeferredItem<Item> DEMONIC_SHOVEL;
	public static final DeferredItem<Item> DEMONIC_HOE;
	public static final DeferredItem<Item> DEMONIC_ARMOR_HELMET;
	public static final DeferredItem<Item> DEMONIC_ARMOR_CHESTPLATE;
	public static final DeferredItem<Item> DEMONIC_ARMOR_LEGGINGS;
	public static final DeferredItem<Item> DEMONIC_ARMOR_BOOTS;
	public static final DeferredItem<Item> THE_ANTIDOTE;
	public static final DeferredItem<Item> STRANGE_STONE;
	public static final DeferredItem<Item> STRANGE_ROCK;
	public static final DeferredItem<Item> STRANGE_PEBBLE;
	public static final DeferredItem<Item> MOSSY_STRANGE_STONE;
	public static final DeferredItem<Item> AQUAPHER_FLOWER;
	public static final DeferredItem<Item> SATURN;
	public static final DeferredItem<Item> STAR_FLOWER;
	public static final DeferredItem<Item> SMOTHE_BONE;
	public static final DeferredItem<Item> BONE_BRICKS;
	public static final DeferredItem<Item> CHIZZELED_BONE;
	public static final DeferredItem<Item> CRACKED_BONE_BRICK;
	public static final DeferredItem<Item> SMOTH_BONE_SLAB;
	public static final DeferredItem<Item> BONE_BRICK_SLAB;
	public static final DeferredItem<Item> CHIZZELED_BONE_SLAB;
	public static final DeferredItem<Item> CRACKED_BONE_BRICK_SLAB;
	public static final DeferredItem<Item> BONE_SLAB;
	public static final DeferredItem<Item> TOSSER_TOT;
	public static final DeferredItem<Item> GUSTAVIUM_BUCKET;
	public static final DeferredItem<Item> TOXIC_WASTE_BUCKET;
	public static final DeferredItem<Item> FIBERGLASS;
	public static final DeferredItem<Item> CLEAR_PLASTC;
	public static final DeferredItem<Item> FIBER_BALL;
	public static final DeferredItem<Item> STILL_SLINGER_SPAWN_EGG;
	public static final DeferredItem<Item> CHOKED_ZOMBIE_SPAWN_EGG;
	public static final DeferredItem<Item> TORN_FIBERS;
	public static final DeferredItem<Item> BLANK_DISC;
	public static final DeferredItem<Item> GLOWING;
	public static final DeferredItem<Item> BRIMSTONE;
	public static final DeferredItem<Item> BRIMSTONE_ORE;
	public static final DeferredItem<Item> BRIMSTONE_BLOCK;
	public static final DeferredItem<Item> BRIMSTONE_PICKAXE;
	public static final DeferredItem<Item> BRIMSTONE_AXE;
	public static final DeferredItem<Item> BRIMSTONE_SWORD;
	public static final DeferredItem<Item> BRIMSTONE_SHOVEL;
	public static final DeferredItem<Item> BRIMSTONE_HOE;
	public static final DeferredItem<Item> BRIMSTONE_ARMOR_HELMET;
	public static final DeferredItem<Item> BRIMSTONE_ARMOR_CHESTPLATE;
	public static final DeferredItem<Item> BRIMSTONE_ARMOR_LEGGINGS;
	public static final DeferredItem<Item> BRIMSTONE_ARMOR_BOOTS;
	public static final DeferredItem<Item> SOULSTONE;
	public static final DeferredItem<Item> SOULSTONE_ORE;
	public static final DeferredItem<Item> SOULSTONE_BLOCK;
	public static final DeferredItem<Item> SOULSTONE_PICKAXE;
	public static final DeferredItem<Item> SOULSTONE_AXE;
	public static final DeferredItem<Item> SOULSTONE_SWORD;
	public static final DeferredItem<Item> SOULSTONE_SHOVEL;
	public static final DeferredItem<Item> SOULSTONE_HOE;
	public static final DeferredItem<Item> SOULSTONE_ARMOR_HELMET;
	public static final DeferredItem<Item> SOULSTONE_ARMOR_CHESTPLATE;
	public static final DeferredItem<Item> SOULSTONE_ARMOR_LEGGINGS;
	public static final DeferredItem<Item> SOULSTONE_ARMOR_BOOTS;
	public static final DeferredItem<Item> MIXOLYDIAN_PICKAXE;
	public static final DeferredItem<Item> MIXOLYDIAN_AXE;
	public static final DeferredItem<Item> MIXOLYDIAN_SWORD;
	public static final DeferredItem<Item> MIXOLYDIAN_SHOVEL;
	public static final DeferredItem<Item> MIXOLYDIAN_HOE;
	public static final DeferredItem<Item> MIXOLYDIAN_ARMOR_HELMET;
	public static final DeferredItem<Item> MIXOLYDIAN_ARMOR_CHESTPLATE;
	public static final DeferredItem<Item> MIXOLYDIAN_ARMOR_LEGGINGS;
	public static final DeferredItem<Item> MIXOLYDIAN_ARMOR_BOOTS;
	public static final DeferredItem<Item> MOON_PEBBLE;
	public static final DeferredItem<Item> FRAGRENT_WOOD;
	public static final DeferredItem<Item> FRAGRENT_LOG;
	public static final DeferredItem<Item> FRAGRENT_PLANKS;
	public static final DeferredItem<Item> FRAGRENT_LEAVES;
	public static final DeferredItem<Item> FRAGRENT_STAIRS;
	public static final DeferredItem<Item> FRAGRENT_SLAB;
	public static final DeferredItem<Item> FRAGRENT_FENCE;
	public static final DeferredItem<Item> FRAGRENT_FENCE_GATE;
	public static final DeferredItem<Item> FRAGRENT_PRESSURE_PLATE;
	public static final DeferredItem<Item> FRAGRENT_BUTTON;
	public static final DeferredItem<Item> REINFORCED_GLASS;
	public static final DeferredItem<Item> TOSSER_BUSH;
	public static final DeferredItem<Item> CROK_VINE;
	public static final DeferredItem<Item> CROK_BULB;
	public static final DeferredItem<Item> CROK_ESSENCE;
	public static final DeferredItem<Item> FOSSIL;
	public static final DeferredItem<Item> DRAGON_FOSSIL;
	public static final DeferredItem<Item> FANCY_CANDLE;
	public static final DeferredItem<Item> UNLIT_FANCY_CANDLE;
	public static final DeferredItem<Item> STRIPPED_FRAGRENT_WOOD;
	public static final DeferredItem<Item> FRAGRENT_BARK;
	public static final DeferredItem<Item> STRIPPED_FRAGRENT_LOG;
	public static final DeferredItem<Item> MARTIAN_SALAD;
	public static final DeferredItem<Item> NIGHTMARE_SPAWN_EGG;
	public static final DeferredItem<Item> MYSTICAL_SHOOTER;
	public static final DeferredItem<Item> ADAMANTIUM_SHOOTER;
	public static final DeferredItem<Item> MOLTEN_SHOOTER;
	public static final DeferredItem<Item> SILVER_BULLET;
	public static final DeferredItem<Item> DREAMDROP_BULLET;
	public static final DeferredItem<Item> FLOWER_CROWN_HELMET;
	public static final DeferredItem<Item> FLOWER_CROWN_CHESTPLATE;
	public static final DeferredItem<Item> LARRY_SPAWN_EGG;
	public static final DeferredItem<Item> H_CRYSTAL;
	public static final DeferredItem<Item> HELIUM_SHARD;
	public static final DeferredItem<Item> GLEEP_GLORP_SPAWN_EGG;
	public static final DeferredItem<Item> ALIEN_HYDE;
	public static final DeferredItem<Item> MEAT;
	public static final DeferredItem<Item> COOKED_MEAT;
	public static final DeferredItem<Item> METEORITE;
	public static final DeferredItem<Item> MOLDEDMETEORITE;
	public static final DeferredItem<Item> CHLORITE;
	public static final DeferredItem<Item> LIGHT_MOON_STONE;
	public static final DeferredItem<Item> DARK_MOON_STONE;
	public static final DeferredItem<Item> LIGHT_MOON_PEBBLE;
	public static final DeferredItem<Item> RAW_SILVER;
	public static final DeferredItem<Item> RAW_DEMONIC_ORE;
	public static final DeferredItem<Item> RAW_SILVER_BLOCK;
	public static final DeferredItem<Item> SNAP_TRAP;
	public static final DeferredItem<Item> POISON_SNAP_TRAP;
	public static final DeferredItem<Item> PLANT_STEM;
	public static final DeferredItem<Item> TV_MEAT;
	static {
		DEBUG_PICK = register("debug_pick", DebugPickItem::new);
		DEBUGGER_SPAWN_EGG = register("debugger_spawn_egg", properties -> new SpawnEggItem(MintyirlplanetsModEntities.DEBUGGER.get(), properties));
		DEBUGGER_ARMOUR_HELMET = register("debugger_armour_helmet", DebuggerArmourItem.Helmet::new);
		DEBUGGER_ARMOUR_CHESTPLATE = register("debugger_armour_chestplate", DebuggerArmourItem.Chestplate::new);
		DEBUGGER_ARMOUR_LEGGINGS = register("debugger_armour_leggings", DebuggerArmourItem.Leggings::new);
		DEBUGGER_ARMOUR_BOOTS = register("debugger_armour_boots", DebuggerArmourItem.Boots::new);
		DISC_1 = register("disc_1", Disc1Item::new);
		DISC_2 = register("disc_2", Disc2Item::new);
		DUMMY_1_HELMET = register("dummy_1_helmet", Dummy1Item.Helmet::new);
		DUMMY_1_CHESTPLATE = register("dummy_1_chestplate", Dummy1Item.Chestplate::new);
		DUMMY_1_LEGGINGS = register("dummy_1_leggings", Dummy1Item.Leggings::new);
		DUMMY_1_BOOTS = register("dummy_1_boots", Dummy1Item.Boots::new);
		DUMMY_2_HELMET = register("dummy_2_helmet", Dummy2Item.Helmet::new);
		DUMMY_2_CHESTPLATE = register("dummy_2_chestplate", Dummy2Item.Chestplate::new);
		DUMMY_2_LEGGINGS = register("dummy_2_leggings", Dummy2Item.Leggings::new);
		DUMMY_2_BOOTS = register("dummy_2_boots", Dummy2Item.Boots::new);
		MOON_ROCK = block(MintyirlplanetsModBlocks.MOON_ROCK, new Item.Properties().stacksTo(99));
		DARK_MOON_ROCK = register("dark_moon_rock", properties -> new DarkMoonRockBlock.Item(properties.stacksTo(99)));
		MOONSHROOM_MOSS = block(MintyirlplanetsModBlocks.MOONSHROOM_MOSS, new Item.Properties().stacksTo(99));
		TERRACELIUM_MOSS = block(MintyirlplanetsModBlocks.TERRACELIUM_MOSS, new Item.Properties().stacksTo(99));
		THE_MOON = register("the_moon", TheMoonItem::new);
		DREAMDROP = register("dreamdrop", DreamdropItem::new);
		DREAMDROP_ORE = block(MintyirlplanetsModBlocks.DREAMDROP_ORE, new Item.Properties().stacksTo(99));
		DREAMDROP_BLOCK = block(MintyirlplanetsModBlocks.DREAMDROP_BLOCK, new Item.Properties().stacksTo(99));
		DREAMDROP_PICKAXE = register("dreamdrop_pickaxe", DreamdropPickaxeItem::new);
		DREAMDROP_AXE = register("dreamdrop_axe", DreamdropAxeItem::new);
		DREAMDROP_SWORD = register("dreamdrop_sword", DreamdropSwordItem::new);
		DREAMDROP_SHOVEL = register("dreamdrop_shovel", DreamdropShovelItem::new);
		DREAMDROP_HOE = register("dreamdrop_hoe", DreamdropHoeItem::new);
		DREAMDROP_ARMOR_HELMET = register("dreamdrop_armor_helmet", DreamdropArmorItem.Helmet::new);
		DREAMDROP_ARMOR_CHESTPLATE = register("dreamdrop_armor_chestplate", DreamdropArmorItem.Chestplate::new);
		DREAMDROP_ARMOR_LEGGINGS = register("dreamdrop_armor_leggings", DreamdropArmorItem.Leggings::new);
		DREAMDROP_ARMOR_BOOTS = register("dreamdrop_armor_boots", DreamdropArmorItem.Boots::new);
		DAMNED_WOOD = block(MintyirlplanetsModBlocks.DAMNED_WOOD, new Item.Properties().stacksTo(99));
		DAMNED_LOG = register("damned_log", properties -> new DamnedLogBlock.Item(properties.stacksTo(99)));
		DAMNED_PLANKS = block(MintyirlplanetsModBlocks.DAMNED_PLANKS, new Item.Properties().stacksTo(99));
		DAMNED_LEAVES = block(MintyirlplanetsModBlocks.DAMNED_LEAVES, new Item.Properties().stacksTo(99));
		DAMNED_STAIRS = block(MintyirlplanetsModBlocks.DAMNED_STAIRS, new Item.Properties().stacksTo(99));
		DAMNED_SLAB = block(MintyirlplanetsModBlocks.DAMNED_SLAB, new Item.Properties().stacksTo(99));
		DAMNED_FENCE = block(MintyirlplanetsModBlocks.DAMNED_FENCE, new Item.Properties().stacksTo(99));
		DAMNED_FENCE_GATE = block(MintyirlplanetsModBlocks.DAMNED_FENCE_GATE, new Item.Properties().stacksTo(99));
		DAMNED_PRESSURE_PLATE = block(MintyirlplanetsModBlocks.DAMNED_PRESSURE_PLATE, new Item.Properties().stacksTo(99));
		DAMNED_BUTTON = block(MintyirlplanetsModBlocks.DAMNED_BUTTON, new Item.Properties().stacksTo(99));
		GLUCOSIDE_EXTRACT = register("glucoside_extract", GlucosideExtractItem::new);
		HELL_FRUIT = register("hell_fruit", HellFruitItem::new);
		REAPER_SPAWN_EGG = register("reaper_spawn_egg", properties -> new SpawnEggItem(MintyirlplanetsModEntities.REAPER.get(), properties));
		SIVER_INGOT = register("siver_ingot", SiverIngotItem::new);
		SIVER_ORE = block(MintyirlplanetsModBlocks.SIVER_ORE, new Item.Properties().stacksTo(99));
		SIVER_BLOCK = block(MintyirlplanetsModBlocks.SIVER_BLOCK, new Item.Properties().stacksTo(99));
		SIVER_PICKAXE = register("siver_pickaxe", SiverPickaxeItem::new);
		SIVER_AXE = register("siver_axe", SiverAxeItem::new);
		SIVER_SWORD = register("siver_sword", SiverSwordItem::new);
		SIVER_SHOVEL = register("siver_shovel", SiverShovelItem::new);
		SIVER_HOE = register("siver_hoe", SiverHoeItem::new);
		SIVER_ARMOR_HELMET = register("siver_armor_helmet", SiverArmorItem.Helmet::new);
		SIVER_ARMOR_CHESTPLATE = register("siver_armor_chestplate", SiverArmorItem.Chestplate::new);
		SIVER_ARMOR_LEGGINGS = register("siver_armor_leggings", SiverArmorItem.Leggings::new);
		SIVER_ARMOR_BOOTS = register("siver_armor_boots", SiverArmorItem.Boots::new);
		ALUMINUM_ORE = block(MintyirlplanetsModBlocks.ALUMINUM_ORE, new Item.Properties().stacksTo(99));
		ALUMINUM_BLOCK = block(MintyirlplanetsModBlocks.ALUMINUM_BLOCK, new Item.Properties().stacksTo(99));
		ALUMINEUM = register("alumineum", AlumineumItem::new);
		ALUMINEUM_BLOCK = block(MintyirlplanetsModBlocks.ALUMINEUM_BLOCK, new Item.Properties().stacksTo(99));
		ALUMINEUM_PICKAXE = register("alumineum_pickaxe", AlumineumPickaxeItem::new);
		ALUMINEUM_AXE = register("alumineum_axe", AlumineumAxeItem::new);
		ALUMINEUM_SWORD = register("alumineum_sword", AlumineumSwordItem::new);
		ALUMINEUM_SHOVEL = register("alumineum_shovel", AlumineumShovelItem::new);
		ALUMINEUM_HOE = register("alumineum_hoe", AlumineumHoeItem::new);
		ALUMINEUM_ARMOR_HELMET = register("alumineum_armor_helmet", AlumineumArmorItem.Helmet::new);
		ALUMINEUM_ARMOR_CHESTPLATE = register("alumineum_armor_chestplate", AlumineumArmorItem.Chestplate::new);
		ALUMINEUM_ARMOR_LEGGINGS = register("alumineum_armor_leggings", AlumineumArmorItem.Leggings::new);
		ALUMINEUM_ARMOR_BOOTS = register("alumineum_armor_boots", AlumineumArmorItem.Boots::new);
		BAUXITE = register("bauxite", BauxiteItem::new);
		MOONSHROOM_2_WOOD = block(MintyirlplanetsModBlocks.MOONSHROOM_2_WOOD, new Item.Properties().stacksTo(99));
		MOONSHROOM_2_LOG = block(MintyirlplanetsModBlocks.MOONSHROOM_2_LOG, new Item.Properties().stacksTo(99));
		MOONSHROOM_2_PLANKS = block(MintyirlplanetsModBlocks.MOONSHROOM_2_PLANKS, new Item.Properties().stacksTo(99));
		MOONSHROOM_2_LEAVES = block(MintyirlplanetsModBlocks.MOONSHROOM_2_LEAVES, new Item.Properties().stacksTo(99));
		MOONSHROOM_2_STAIRS = block(MintyirlplanetsModBlocks.MOONSHROOM_2_STAIRS, new Item.Properties().stacksTo(99));
		MOONSHROOM_2_SLAB = block(MintyirlplanetsModBlocks.MOONSHROOM_2_SLAB, new Item.Properties().stacksTo(99));
		MOONSHROOM_2_FENCE = block(MintyirlplanetsModBlocks.MOONSHROOM_2_FENCE, new Item.Properties().stacksTo(99));
		MOONSHROOM_2_FENCE_GATE = block(MintyirlplanetsModBlocks.MOONSHROOM_2_FENCE_GATE, new Item.Properties().stacksTo(99));
		MOONSHROOM_2_PRESSURE_PLATE = block(MintyirlplanetsModBlocks.MOONSHROOM_2_PRESSURE_PLATE, new Item.Properties().stacksTo(99));
		MOONSHROOM_2_BUTTON = block(MintyirlplanetsModBlocks.MOONSHROOM_2_BUTTON, new Item.Properties().stacksTo(99));
		MOONSHROOM_SPORESCONNECTOR = block(MintyirlplanetsModBlocks.MOONSHROOM_SPORESCONNECTOR, new Item.Properties().stacksTo(99));
		MOONSHROOM_SPORES = block(MintyirlplanetsModBlocks.MOONSHROOM_SPORES, new Item.Properties().stacksTo(99));
		MOONSHROOM_STEM = block(MintyirlplanetsModBlocks.MOONSHROOM_STEM, new Item.Properties().stacksTo(99));
		COLD_DUST = register("cold_dust", ColdDustItem::new);
		LAZER_SHOOTER = register("lazer_shooter", LazerShooterItem::new);
		EYEZOR_SPAWN_EGG = register("eyezor_spawn_egg", properties -> new SpawnEggItem(MintyirlplanetsModEntities.EYEZOR.get(), properties));
		DARK_MOONDISC = register("dark_moondisc", DarkMoondiscItem::new);
		STRANGE_ENERGY = register("strange_energy", StrangeEnergyItem::new);
		ANTIMATTER = register("antimatter", AntimatterItem::new);
		KRYPTONIUM = register("kryptonium", KryptoniumItem::new);
		KRYPTONIUM_ORE = block(MintyirlplanetsModBlocks.KRYPTONIUM_ORE, new Item.Properties().stacksTo(99));
		KRYPTONIUM_BLOCK = block(MintyirlplanetsModBlocks.KRYPTONIUM_BLOCK, new Item.Properties().stacksTo(99));
		KRYPTONIUM_PICKAXE = register("kryptonium_pickaxe", KryptoniumPickaxeItem::new);
		KRYPTONIUM_AXE = register("kryptonium_axe", KryptoniumAxeItem::new);
		KRYPTONIUM_SWORD = register("kryptonium_sword", KryptoniumSwordItem::new);
		KRYPTONIUM_SHOVEL = register("kryptonium_shovel", KryptoniumShovelItem::new);
		KRYPTONIUM_HOE = register("kryptonium_hoe", KryptoniumHoeItem::new);
		KRYPTONIUM_ARMOR_HELMET = register("kryptonium_armor_helmet", KryptoniumArmorItem.Helmet::new);
		KRYPTONIUM_ARMOR_CHESTPLATE = register("kryptonium_armor_chestplate", KryptoniumArmorItem.Chestplate::new);
		KRYPTONIUM_ARMOR_LEGGINGS = register("kryptonium_armor_leggings", KryptoniumArmorItem.Leggings::new);
		KRYPTONIUM_ARMOR_BOOTS = register("kryptonium_armor_boots", KryptoniumArmorItem.Boots::new);
		THE_CRUSHER_SPAWN_EGG = register("the_crusher_spawn_egg", properties -> new SpawnEggItem(MintyirlplanetsModEntities.THE_CRUSHER.get(), properties));
		FERROUS_SAND = block(MintyirlplanetsModBlocks.FERROUS_SAND, new Item.Properties().stacksTo(99));
		SPACE_HELMET = register("space_helmet", SpaceItem.Helmet::new);
		SPACE_CHESTPLATE = register("space_chestplate", SpaceItem.Chestplate::new);
		SPACE_LEGGINGS = register("space_leggings", SpaceItem.Leggings::new);
		SPACE_BOOTS = register("space_boots", SpaceItem.Boots::new);
		MARS = register("mars", MarsItem::new);
		MARTIAN_SPAWN_EGG = register("martian_spawn_egg", properties -> new SpawnEggItem(MintyirlplanetsModEntities.MARTIAN.get(), properties));
		SHRUMPHER_SPAWN_EGG = register("shrumpher_spawn_egg", properties -> new SpawnEggItem(MintyirlplanetsModEntities.SHRUMPHER.get(), properties));
		CORESTONE = block(MintyirlplanetsModBlocks.CORESTONE, new Item.Properties().stacksTo(99));
		CROATIAN_WOOD = block(MintyirlplanetsModBlocks.CROATIAN_WOOD, new Item.Properties().stacksTo(99));
		CROATIAN_LOG = block(MintyirlplanetsModBlocks.CROATIAN_LOG, new Item.Properties().stacksTo(99));
		CROATIAN_PLANKS = block(MintyirlplanetsModBlocks.CROATIAN_PLANKS, new Item.Properties().stacksTo(99));
		CROATIAN_LEAVES = block(MintyirlplanetsModBlocks.CROATIAN_LEAVES, new Item.Properties().stacksTo(99));
		CROATIAN_STAIRS = block(MintyirlplanetsModBlocks.CROATIAN_STAIRS, new Item.Properties().stacksTo(99));
		CROATIAN_SLAB = block(MintyirlplanetsModBlocks.CROATIAN_SLAB, new Item.Properties().stacksTo(99));
		CROATIAN_FENCE = block(MintyirlplanetsModBlocks.CROATIAN_FENCE, new Item.Properties().stacksTo(99));
		CROATIAN_FENCE_GATE = block(MintyirlplanetsModBlocks.CROATIAN_FENCE_GATE, new Item.Properties().stacksTo(99));
		CROATIAN_PRESSURE_PLATE = block(MintyirlplanetsModBlocks.CROATIAN_PRESSURE_PLATE, new Item.Properties().stacksTo(99));
		CROATIAN_BUTTON = block(MintyirlplanetsModBlocks.CROATIAN_BUTTON, new Item.Properties().stacksTo(99));
		MUSIC_DISC_MARS = register("music_disc_mars", MusicDiscMarsItem::new);
		ADAMANTIUMM = register("adamantiumm", AdamantiummItem::new);
		ADAMANTIUMM_ORE = block(MintyirlplanetsModBlocks.ADAMANTIUMM_ORE, new Item.Properties().stacksTo(99));
		ADAMANTIUMM_BLOCK = block(MintyirlplanetsModBlocks.ADAMANTIUMM_BLOCK, new Item.Properties().stacksTo(99));
		ADAMANTIUMM_PICKAXE = register("adamantiumm_pickaxe", AdamantiummPickaxeItem::new);
		ADAMANTIUMM_AXE = register("adamantiumm_axe", AdamantiummAxeItem::new);
		ADAMANTIUMM_SWORD = register("adamantiumm_sword", AdamantiummSwordItem::new);
		ADAMANTIUMM_SHOVEL = register("adamantiumm_shovel", AdamantiummShovelItem::new);
		ADAMANTIUMM_HOE = register("adamantiumm_hoe", AdamantiummHoeItem::new);
		ADAMANTIUMM_ARMOR_HELMET = register("adamantiumm_armor_helmet", AdamantiummArmorItem.Helmet::new);
		ADAMANTIUMM_ARMOR_CHESTPLATE = register("adamantiumm_armor_chestplate", AdamantiummArmorItem.Chestplate::new);
		ADAMANTIUMM_ARMOR_LEGGINGS = register("adamantiumm_armor_leggings", AdamantiummArmorItem.Leggings::new);
		ADAMANTIUMM_ARMOR_BOOTS = register("adamantiumm_armor_boots", AdamantiummArmorItem.Boots::new);
		RAW_ADAMANTIUM = register("raw_adamantium", RawAdamantiumItem::new);
		DEMONIC_INGOT = register("demonic_ingot", DemonicIngotItem::new);
		DEMONIC_ORE = block(MintyirlplanetsModBlocks.DEMONIC_ORE, new Item.Properties().stacksTo(99));
		DEMONIC_BLOCK = block(MintyirlplanetsModBlocks.DEMONIC_BLOCK, new Item.Properties().stacksTo(99));
		DEMONIC_PICKAXE = register("demonic_pickaxe", DemonicPickaxeItem::new);
		DEMONIC_AXE = register("demonic_axe", DemonicAxeItem::new);
		DEMONIC_SWORD = register("demonic_sword", DemonicSwordItem::new);
		DEMONIC_SHOVEL = register("demonic_shovel", DemonicShovelItem::new);
		DEMONIC_HOE = register("demonic_hoe", DemonicHoeItem::new);
		DEMONIC_ARMOR_HELMET = register("demonic_armor_helmet", DemonicArmorItem.Helmet::new);
		DEMONIC_ARMOR_CHESTPLATE = register("demonic_armor_chestplate", DemonicArmorItem.Chestplate::new);
		DEMONIC_ARMOR_LEGGINGS = register("demonic_armor_leggings", DemonicArmorItem.Leggings::new);
		DEMONIC_ARMOR_BOOTS = register("demonic_armor_boots", DemonicArmorItem.Boots::new);
		THE_ANTIDOTE = register("the_antidote", TheAntidoteItem::new);
		STRANGE_STONE = block(MintyirlplanetsModBlocks.STRANGE_STONE, new Item.Properties().stacksTo(99));
		STRANGE_ROCK = block(MintyirlplanetsModBlocks.STRANGE_ROCK, new Item.Properties().stacksTo(99));
		STRANGE_PEBBLE = register("strange_pebble", StrangePebbleItem::new);
		MOSSY_STRANGE_STONE = block(MintyirlplanetsModBlocks.MOSSY_STRANGE_STONE, new Item.Properties().stacksTo(99));
		AQUAPHER_FLOWER = block(MintyirlplanetsModBlocks.AQUAPHER_FLOWER, new Item.Properties().stacksTo(99));
		SATURN = register("saturn", SaturnItem::new);
		STAR_FLOWER = block(MintyirlplanetsModBlocks.STAR_FLOWER, new Item.Properties().stacksTo(99));
		SMOTHE_BONE = block(MintyirlplanetsModBlocks.SMOTHE_BONE, new Item.Properties().stacksTo(99));
		BONE_BRICKS = block(MintyirlplanetsModBlocks.BONE_BRICKS, new Item.Properties().stacksTo(99));
		CHIZZELED_BONE = block(MintyirlplanetsModBlocks.CHIZZELED_BONE, new Item.Properties().stacksTo(99));
		CRACKED_BONE_BRICK = block(MintyirlplanetsModBlocks.CRACKED_BONE_BRICK, new Item.Properties().stacksTo(99));
		SMOTH_BONE_SLAB = block(MintyirlplanetsModBlocks.SMOTH_BONE_SLAB, new Item.Properties().stacksTo(99));
		BONE_BRICK_SLAB = block(MintyirlplanetsModBlocks.BONE_BRICK_SLAB, new Item.Properties().stacksTo(99));
		CHIZZELED_BONE_SLAB = block(MintyirlplanetsModBlocks.CHIZZELED_BONE_SLAB, new Item.Properties().stacksTo(99));
		CRACKED_BONE_BRICK_SLAB = block(MintyirlplanetsModBlocks.CRACKED_BONE_BRICK_SLAB, new Item.Properties().stacksTo(99));
		BONE_SLAB = block(MintyirlplanetsModBlocks.BONE_SLAB, new Item.Properties().stacksTo(99));
		TOSSER_TOT = register("tosser_tot", TosserTotItem::new);
		GUSTAVIUM_BUCKET = register("gustavium_bucket", GustaviumItem::new);
		TOXIC_WASTE_BUCKET = register("toxic_waste_bucket", ToxicWasteItem::new);
		FIBERGLASS = block(MintyirlplanetsModBlocks.FIBERGLASS, new Item.Properties().stacksTo(99));
		CLEAR_PLASTC = block(MintyirlplanetsModBlocks.CLEAR_PLASTC, new Item.Properties().stacksTo(99));
		FIBER_BALL = register("fiber_ball", FiberBallItem::new);
		STILL_SLINGER_SPAWN_EGG = register("still_slinger_spawn_egg", properties -> new SpawnEggItem(MintyirlplanetsModEntities.STILL_SLINGER.get(), properties));
		CHOKED_ZOMBIE_SPAWN_EGG = register("choked_zombie_spawn_egg", properties -> new SpawnEggItem(MintyirlplanetsModEntities.CHOKED_ZOMBIE.get(), properties));
		TORN_FIBERS = register("torn_fibers", TornFibersItem::new);
		BLANK_DISC = register("blank_disc", BlankDiscItem::new);
		GLOWING = block(MintyirlplanetsModBlocks.GLOWING, new Item.Properties().stacksTo(99));
		BRIMSTONE = register("brimstone", BrimstoneItem::new);
		BRIMSTONE_ORE = register("brimstone_ore", properties -> new BrimstoneOreBlock.Item(properties.stacksTo(99)));
		BRIMSTONE_BLOCK = block(MintyirlplanetsModBlocks.BRIMSTONE_BLOCK, new Item.Properties().stacksTo(99));
		BRIMSTONE_PICKAXE = register("brimstone_pickaxe", BrimstonePickaxeItem::new);
		BRIMSTONE_AXE = register("brimstone_axe", BrimstoneAxeItem::new);
		BRIMSTONE_SWORD = register("brimstone_sword", BrimstoneSwordItem::new);
		BRIMSTONE_SHOVEL = register("brimstone_shovel", BrimstoneShovelItem::new);
		BRIMSTONE_HOE = register("brimstone_hoe", BrimstoneHoeItem::new);
		BRIMSTONE_ARMOR_HELMET = register("brimstone_armor_helmet", BrimstoneArmorItem.Helmet::new);
		BRIMSTONE_ARMOR_CHESTPLATE = register("brimstone_armor_chestplate", BrimstoneArmorItem.Chestplate::new);
		BRIMSTONE_ARMOR_LEGGINGS = register("brimstone_armor_leggings", BrimstoneArmorItem.Leggings::new);
		BRIMSTONE_ARMOR_BOOTS = register("brimstone_armor_boots", BrimstoneArmorItem.Boots::new);
		SOULSTONE = register("soulstone", SoulstoneItem::new);
		SOULSTONE_ORE = block(MintyirlplanetsModBlocks.SOULSTONE_ORE, new Item.Properties().stacksTo(99));
		SOULSTONE_BLOCK = block(MintyirlplanetsModBlocks.SOULSTONE_BLOCK, new Item.Properties().stacksTo(99));
		SOULSTONE_PICKAXE = register("soulstone_pickaxe", SoulstonePickaxeItem::new);
		SOULSTONE_AXE = register("soulstone_axe", SoulstoneAxeItem::new);
		SOULSTONE_SWORD = register("soulstone_sword", SoulstoneSwordItem::new);
		SOULSTONE_SHOVEL = register("soulstone_shovel", SoulstoneShovelItem::new);
		SOULSTONE_HOE = register("soulstone_hoe", SoulstoneHoeItem::new);
		SOULSTONE_ARMOR_HELMET = register("soulstone_armor_helmet", SoulstoneArmorItem.Helmet::new);
		SOULSTONE_ARMOR_CHESTPLATE = register("soulstone_armor_chestplate", SoulstoneArmorItem.Chestplate::new);
		SOULSTONE_ARMOR_LEGGINGS = register("soulstone_armor_leggings", SoulstoneArmorItem.Leggings::new);
		SOULSTONE_ARMOR_BOOTS = register("soulstone_armor_boots", SoulstoneArmorItem.Boots::new);
		MIXOLYDIAN_PICKAXE = register("mixolydian_pickaxe", MixolydianPickaxeItem::new);
		MIXOLYDIAN_AXE = register("mixolydian_axe", MixolydianAxeItem::new);
		MIXOLYDIAN_SWORD = register("mixolydian_sword", MixolydianSwordItem::new);
		MIXOLYDIAN_SHOVEL = register("mixolydian_shovel", MixolydianShovelItem::new);
		MIXOLYDIAN_HOE = register("mixolydian_hoe", MixolydianHoeItem::new);
		MIXOLYDIAN_ARMOR_HELMET = register("mixolydian_armor_helmet", MixolydianArmorItem.Helmet::new);
		MIXOLYDIAN_ARMOR_CHESTPLATE = register("mixolydian_armor_chestplate", MixolydianArmorItem.Chestplate::new);
		MIXOLYDIAN_ARMOR_LEGGINGS = register("mixolydian_armor_leggings", MixolydianArmorItem.Leggings::new);
		MIXOLYDIAN_ARMOR_BOOTS = register("mixolydian_armor_boots", MixolydianArmorItem.Boots::new);
		MOON_PEBBLE = register("moon_pebble", MoonPebbleItem::new);
		FRAGRENT_WOOD = block(MintyirlplanetsModBlocks.FRAGRENT_WOOD, new Item.Properties().stacksTo(99));
		FRAGRENT_LOG = register("fragrent_log", properties -> new FragrentLogBlock.Item(properties.stacksTo(99)));
		FRAGRENT_PLANKS = block(MintyirlplanetsModBlocks.FRAGRENT_PLANKS, new Item.Properties().stacksTo(99));
		FRAGRENT_LEAVES = block(MintyirlplanetsModBlocks.FRAGRENT_LEAVES, new Item.Properties().stacksTo(99));
		FRAGRENT_STAIRS = block(MintyirlplanetsModBlocks.FRAGRENT_STAIRS, new Item.Properties().stacksTo(99));
		FRAGRENT_SLAB = block(MintyirlplanetsModBlocks.FRAGRENT_SLAB, new Item.Properties().stacksTo(99));
		FRAGRENT_FENCE = block(MintyirlplanetsModBlocks.FRAGRENT_FENCE, new Item.Properties().stacksTo(99));
		FRAGRENT_FENCE_GATE = block(MintyirlplanetsModBlocks.FRAGRENT_FENCE_GATE, new Item.Properties().stacksTo(99));
		FRAGRENT_PRESSURE_PLATE = block(MintyirlplanetsModBlocks.FRAGRENT_PRESSURE_PLATE, new Item.Properties().stacksTo(99));
		FRAGRENT_BUTTON = block(MintyirlplanetsModBlocks.FRAGRENT_BUTTON, new Item.Properties().stacksTo(99));
		REINFORCED_GLASS = block(MintyirlplanetsModBlocks.REINFORCED_GLASS, new Item.Properties().stacksTo(4));
		TOSSER_BUSH = block(MintyirlplanetsModBlocks.TOSSER_BUSH, new Item.Properties().stacksTo(99));
		CROK_VINE = block(MintyirlplanetsModBlocks.CROK_VINE, new Item.Properties().stacksTo(99));
		CROK_BULB = block(MintyirlplanetsModBlocks.CROK_BULB, new Item.Properties().stacksTo(99));
		CROK_ESSENCE = register("crok_essence", CrokEssenceItem::new);
		FOSSIL = block(MintyirlplanetsModBlocks.FOSSIL, new Item.Properties().stacksTo(99));
		DRAGON_FOSSIL = register("dragon_fossil", DragonFossilItem::new);
		FANCY_CANDLE = block(MintyirlplanetsModBlocks.FANCY_CANDLE, new Item.Properties().stacksTo(99).fireResistant());
		UNLIT_FANCY_CANDLE = block(MintyirlplanetsModBlocks.UNLIT_FANCY_CANDLE, new Item.Properties().stacksTo(70).fireResistant());
		STRIPPED_FRAGRENT_WOOD = block(MintyirlplanetsModBlocks.STRIPPED_FRAGRENT_WOOD, new Item.Properties().stacksTo(99));
		FRAGRENT_BARK = register("fragrent_bark", FragrentBarkItem::new);
		STRIPPED_FRAGRENT_LOG = block(MintyirlplanetsModBlocks.STRIPPED_FRAGRENT_LOG, new Item.Properties().stacksTo(99));
		MARTIAN_SALAD = register("martian_salad", MartianSaladItem::new);
		NIGHTMARE_SPAWN_EGG = register("nightmare_spawn_egg", properties -> new SpawnEggItem(MintyirlplanetsModEntities.NIGHTMARE.get(), properties));
		MYSTICAL_SHOOTER = register("mystical_shooter", MysticalShooterItem::new);
		ADAMANTIUM_SHOOTER = register("adamantium_shooter", AdamantiumShooterItem::new);
		MOLTEN_SHOOTER = register("molten_shooter", MoltenShooterItem::new);
		SILVER_BULLET = register("silver_bullet", SilverBulletItem::new);
		DREAMDROP_BULLET = register("dreamdrop_bullet", DreamdropBulletItem::new);
		FLOWER_CROWN_HELMET = register("flower_crown_helmet", FlowerCrownItem.Helmet::new);
		FLOWER_CROWN_CHESTPLATE = register("flower_crown_chestplate", FlowerCrownItem.Chestplate::new);
		LARRY_SPAWN_EGG = register("larry_spawn_egg", properties -> new SpawnEggItem(MintyirlplanetsModEntities.LARRY.get(), properties));
		H_CRYSTAL = block(MintyirlplanetsModBlocks.H_CRYSTAL, new Item.Properties().stacksTo(67));
		HELIUM_SHARD = register("helium_shard", HeliumShardItem::new);
		GLEEP_GLORP_SPAWN_EGG = register("gleep_glorp_spawn_egg", properties -> new SpawnEggItem(MintyirlplanetsModEntities.GLEEP_GLORP.get(), properties));
		ALIEN_HYDE = register("alien_hyde", AlienHydeItem::new);
		MEAT = register("meat", MeatItem::new);
		COOKED_MEAT = register("cooked_meat", CookedMeatItem::new);
		METEORITE = block(MintyirlplanetsModBlocks.METEORITE, new Item.Properties().stacksTo(99));
		MOLDEDMETEORITE = register("moldedmeteorite", MoldedmeteoriteItem::new);
		CHLORITE = block(MintyirlplanetsModBlocks.CHLORITE);
		LIGHT_MOON_STONE = block(MintyirlplanetsModBlocks.LIGHT_MOON_STONE, new Item.Properties().stacksTo(99));
		DARK_MOON_STONE = block(MintyirlplanetsModBlocks.DARK_MOON_STONE, new Item.Properties().stacksTo(99));
		LIGHT_MOON_PEBBLE = register("light_moon_pebble", LightMoonPebbleItem::new);
		RAW_SILVER = register("raw_silver", RawSilverItem::new);
		RAW_DEMONIC_ORE = register("raw_demonic_ore", RawDemonicOreItem::new);
		RAW_SILVER_BLOCK = block(MintyirlplanetsModBlocks.RAW_SILVER_BLOCK, new Item.Properties().stacksTo(99));
		SNAP_TRAP = block(MintyirlplanetsModBlocks.SNAP_TRAP, new Item.Properties().stacksTo(99).rarity(Rarity.RARE));
		POISON_SNAP_TRAP = block(MintyirlplanetsModBlocks.POISON_SNAP_TRAP, new Item.Properties().stacksTo(99).rarity(Rarity.RARE));
		PLANT_STEM = register("plant_stem", PlantStemItem::new);
		TV_MEAT = register("tv_meat", TvMeatItem::new);
	}

	// Start of user code block custom items
	// End of user code block custom items
	private static <I extends Item> DeferredItem<I> register(String name, Function<Item.Properties, ? extends I> supplier) {
		return REGISTRY.registerItem(name, supplier, new Item.Properties());
	}

	private static DeferredItem<Item> block(DeferredHolder<Block, Block> block) {
		return block(block, new Item.Properties());
	}

	private static DeferredItem<Item> block(DeferredHolder<Block, Block> block, Item.Properties properties) {
		return REGISTRY.registerItem(block.getId().getPath(), prop -> new BlockItem(block.get(), prop), properties);
	}

	@SubscribeEvent
	public static void registerCapabilities(RegisterCapabilitiesEvent event) {
		event.registerItem(Capabilities.FluidHandler.ITEM, (stack, context) -> new FluidBucketWrapper(stack), GUSTAVIUM_BUCKET.get());
		event.registerItem(Capabilities.FluidHandler.ITEM, (stack, context) -> new FluidBucketWrapper(stack), TOXIC_WASTE_BUCKET.get());
	}
}